---
- name: Create a Kolla-Ansible Multihost Inventory file (/etc/kolla/config/inventory/multinode)
  hosts: 127.0.0.1
  connection: local
  become: True
  gather_facts: False
  roles:
    - create_multihost
