---
- name: Gather nova list output
  hosts: localhost
  connection: local
  shell: "source /home/stack/stackrc && nova list"
  register: command_output

- name: Count Controllers
  hosts: localhost
  connection: local
  shell: source /home/stack/stackrc && nova list | awk '/overcloud-controller/ { count++ } END { print count }'
  register: countControllers

- name: Count Computes
  hosts: localhost
  connection: local
  shell: source /home/stack/stackrc && nova list | awk '/overcloud-ovscompute/ { count++ } END { print count }'
  register: countComputes

- name: Grab Controller name
  hosts: localhost
  connection: local
  shell: O=`source /home/stack/stackrc && nova list | grep 'controller' | grep '\-0' | awk ' {print $4}'`; echo "${O//-0}"
  register: nameController

- name: Grab Compute name
  hosts: localhost
  connection: local
  shell: O=`source /home/stack/stackrc && nova list | grep 'compute' | grep '\-0' | awk ' {print $4}'`; echo "${O//-0}"
  register: nameCompute

- name: Copy existing Multinode Inventory file
  hosts: localhost
  connection: local
  copy:
     src: /etc/kolla/config/inventory/multinode
     dest: /etc/kolla/config/inventory/multinode.save

- name: Create Multinode Inventory file
  hosts: localhost
  connection: local
  template: 
    src: multinode.j2 
    dest: /etc/kolla/config/inventory/multinode
